# $schema: ./.smtp-server/smtp-server-schema.json
# https://www.jetbrains.com/help/idea/yaml.html#use-schema-keyword
#
# This file is the dev/test configuration file
#
# The separators in key are points
# to be consistent with the configuration of Java Mail
softwareName: My Smtp Server # software name advertised in the banner
authLocalhostRequired: false # localhost does not need any authentication
sessionReplayEnabled: true # print the session on stdout at the end of the session
keyPath: src/test/resources/ssl/key.pem # the path to the private key
certificatePath: src/test/resources/ssl/cert.pem # the path to the certificate
# The services started by ports
# key in jsonSchema is string
services:
  2525: # port 2525 (PaperCut got already the port 25)
    tlsEnabled: false # start as plain connection
    startTlsEnabled: true # may upgrade the connection to TLS
    startTlsRequired: false # upgrading the connection to TLS is mandatory (false for PaperCut)
    authRequired: false # no authentication is required
  25465: # SSL port
    tlsEnabled: true # start as TLS connection
    startTlsEnabled: false # as we have a TLS connection
    authRequired: true # auth is required, it may not for local delivery, but we use it to test
host: mx1.example.dev # the host and default host (chosen when the connection is not secured (no TLS) as we don't have the requested host)
hosts: # the hosted hosts by hostname
  mx1.example.dev: # the virtual host name (ie DNS cname)
    domain: example.dev # the email domain
    postmaster: alice@gmail.dev # the postmaster email
  smtp.example.dev:
    domain: example.dev
    postmaster: bob@gmail.dev
    keyPath: src/test/resources/ssl/key.pem # the path to the private key
    certificatePath: src/test/resources/ssl/cert.pem # the path to the certificate
  smtp.world.dev:
    domain: hallo.dev
    postmaster: bob@gmail.dev

# Http server port (for prometheus metrics and rest)
httpPort: 25026

# System limits
limits:
  idleConnectionTimeoutSecond: 50 # to allow long debug session
  handShakeTimeoutSecond: 10 # the default
  maxTotalConnections: 50 # the maximum total of connection/sockets
  maxConnectionByIp: 3 # the maximum total of sockets by remote ip
  maxMessageSizeInBytes: 1048576 # the maximum message size in bytes 1 Mo
  maximumExceptionCountBySession: 3 # the maximum number of exception by session
  maxRecipientsByEmail: 100 # the maximum number of recipients (should be bigger or equal to 100 as specified in the spec)

# Delivery
delivery:
  # delivery.quota.remote: 200 # by day by account (same as SES by account)
  # delivery.quota.remote.rate: 1 # by second by account (same as SES by account)
  retryInterval: 15 # minutes, the interval in which a failed delivery is not retried
  immediateDelivery: true # deliver the message immediately after reception
  runInterval: 1 # minutes (if 0 not delivery occurs at interval)

# Reception
reception:
  enableDnsBlockList: true # by default false because not home but on cloud host, the DNS is public, and it then does not work

# Users
users:
  # domain
  example.dev:
    # memory is to test email reception
    memory:
      password: secret
      mailbox:
        type: memory # an in-memory map, so that we can retrieve the email
    # dmarc-memory is to test dmarc email
    dmarc-memory:
      mailbox:
        type: memory
        milters:
          - dmarc
    # dmarc-s3 is to send a dmarc email to s3
    dmarc-s3:
      mailbox:
        type: s3
        milters:
          - dmarc
        props:
          s3.bucket.name: 'dmarc-dev'
          s3.region: 'ca-mtl'
          s3.url.endpoint: 'https://h0k0.ca.idrivee2-22.com'
        # in the s3 local credentials file or in env:
        #  s3.access.key.id: ACCESS_KEY_ID
        #  s3.secret.access.key: SECRET_ACCESS_KEY
